name: Build and Release Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Clean install
        shell: cmd
        run: |
          if exist node_modules rd /s /q node_modules
          npm ci

      - name: Build app
        run: npm run build

      - name: Prepare NSIS license
        shell: powershell
        run: |
          $path = "resources/license.txt"
          $content = Get-Content -Path $path -Raw -Encoding UTF8
          [System.IO.File]::WriteAllText(
            $path,
            $content,
            [System.Text.Encoding]::GetEncoding(1252)
          )

      - name: Package Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron:build

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist-installer/*.exe
          retention-days: 3
